// This file was auto-generated by prisma-generator-typescript-interfaces

export type Role = "admin" | "user" | "editor";

export type Provider = "google" | "facebook" | "github" | "microsoft";

export interface User {
  id: number;
  firstName: string | null;
  lastName: string | null;
  picture: string | null;
  email: string;
  catalog?: Catalog[];
  /**
   * @TypeGraphQL.omit(output: true)
   */
  password: string | null;
  refreshToken: string | null;
  createdAt: Date;
  updatedAt: Date;
  role: Role;
  provider: Provider[];
}

export interface Catalog {
  id: number;
  title: string | null;
  description: string | null;
  type: string | null;
  author: string | null;
  owner?: User;
  ownerId: number;
}
